### ISSUE TITLE
forge not working with darkness lib mod

### ISSUE THREAD

**Issue by DMBurch06** [Shinoow/DarknessLib#1]
Hello,
I am trying to get Minecraft forge to open with some mods for my nephew. I keep getting errors on opening forge and it's saying I need the right versions of Minecraft in order to do so and I keep getting the following screen
![Screenshot (2)](https://user-images.githubusercontent.com/59068838/71212692-acd6fa80-2266-11ea-8fcc-b45ec2ea803f.png)

I don't understand because I have downloaded the correct version. Any help would be really appreciated!

Thanks

**Comment by Shinoow** [comment]
See https://github.com/Shinoow/Grue/issues/21#issuecomment-568271429
