### ISSUE TITLE
Not working with smooth entity light 4.0.4

### ISSUE THREAD

**Issue by kappa-maintainer** [Shinoow/DarknessLib#2]
Tested with forge version 14.23.5.2854, light sources from Atomic Stryker's Dynamic Lights did change light level, but Smooth Entity Light's didn't.

**Comment by chev2** [comment]
I'm having the same exact issue. Did you ever figure it out? I'm using version 4.0.4 on Minecraft 1.12.2 with Forge version 14.23.5.2855.
